### ISSUE TITLE
Feature Request: Set profile via environment variable

### ISSUE THREAD

**Issue by rschmukler** [juxt/aero#87]
In the case of 12 factor applications, it can be useful to select the profile via a single environment variable. Perhaps defaulting profile to a parser reading the `ENV` environment variable?

```
ENV=production java my-awesome-app.jar
```

If aero wanted to be less opinionated, it could even be configured via the options map:

```clj
(aero/read-config "config.edn" {:profile-var "ENV"})
```

Happy to submit a PR if this is something that could be added. I also buy that this can be done in a per-project config namespace (sourcing the env var, parsing it to keyword, and using it) so maybe it's not worth it.

**Comment by SevereOverfl0w** [comment]
I don't think this is something Aero would take part in.  Aero is easily composed with the existing tools to make this happen, in particular: `(aero/read-config "config.edn" {:profile (keyword (or (System/getenv "PROFILE") "default"))})`.

Aero would otherwise have to make decisions about fallback/missing behaviour, and also becomes more complex.

**Comment by rschmukler** [comment]
Makes sense! Thanks for the reply.
